server {
    listen 8081;
    server_name _;

    root /usr/share/nginx/html;
    index index.html;

    location / {
        return 200 "DEBUG NGINX: Llegaste al contenedor web-softpichanga en el puerto 8081. URI solicitada: $request_uri";
        add_header Content-Type text/plain;
    }
}
