// <auto-generated />
using System;
using HSPichanga.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace HSPichanga.Infrastructure.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260417050940_AddEstadoCanchaReprogramacion")]
    partial class AddEstadoCanchaReprogramacion
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("public")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("HSPichanga.Domain.Entities.Cancha", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<decimal>("CostoTotal")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Direccion")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<int>("EstadoCancha")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<int>("JugadoresRequeridos")
                        .HasColumnType("integer");

                    b.Property<int>("Modalidad")
                        .HasColumnType("integer");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<bool>("TieneEstacionamiento")
                        .HasColumnType("boolean");

                    b.Property<bool>("TieneLuz")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ZonaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ZonaId");

                    b.ToTable("Canchas", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            Activo = true,
                            CostoTotal = 280.00m,
                            Descripcion = "Cancha de grass sintético con iluminación LED profesional",
                            Direccion = "Av. Larco 1200, Miraflores",
                            EstadoCancha = 1,
                            JugadoresRequeridos = 14,
                            Modalidad = 2,
                            Nombre = "Cancha Central ADHSOFT",
                            TieneEstacionamiento = true,
                            TieneLuz = true,
                            ZonaId = new Guid("11111111-1111-1111-1111-111111111111")
                        });
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Club", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("DelegadoId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("LogoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreClub")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.HasIndex("DelegadoId");

                    b.ToTable("Clubs", "public");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.HorarioDisponible", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("DiaSemana")
                        .HasColumnType("integer");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.ToTable("HorariosDisponibles", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("7619dceb-27b3-4a13-be5b-0df186e033b7"),
                            Activo = true,
                            CanchaId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DiaSemana = 1,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("b64076d0-bd17-4ba6-be98-f156e94c8009"),
                            Activo = true,
                            CanchaId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DiaSemana = 3,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("35e854bc-f83a-440e-b489-c92e6bca39d5"),
                            Activo = true,
                            CanchaId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DiaSemana = 5,
                            HoraFin = new TimeSpan(0, 20, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 18, 0, 0, 0)
                        },
                        new
                        {
                            Id = new Guid("1c7aef4f-2c38-4d2d-82b9-912db04703bd"),
                            Activo = true,
                            CanchaId = new Guid("cccccccc-cccc-cccc-cccc-cccccccccccc"),
                            DiaSemana = 6,
                            HoraFin = new TimeSpan(0, 12, 0, 0, 0),
                            HoraInicio = new TimeSpan(0, 10, 0, 0, 0)
                        });
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Partido", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("CanchaId")
                        .HasColumnType("uuid");

                    b.Property<int>("Categoria")
                        .HasColumnType("integer");

                    b.Property<decimal>("CuotaIndividual")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("CuposOcupados")
                        .HasColumnType("integer");

                    b.Property<int>("CuposTotales")
                        .HasColumnType("integer");

                    b.Property<int>("Estado")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FechaHora")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("FechaReprogramada")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("HorarioId")
                        .HasColumnType("uuid");

                    b.Property<string>("Notas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<Guid>("OrganizadorId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("TarifaEquipo")
                        .HasColumnType("decimal(10,2)");

                    b.Property<int>("TipoPartido")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("CanchaId");

                    b.HasIndex("HorarioId");

                    b.HasIndex("OrganizadorId");

                    b.ToTable("Partidos", "public");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Reserva", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CodigoConfirmacion")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<int>("EstadoPago")
                        .HasColumnType("integer");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("JugadorId")
                        .HasColumnType("uuid");

                    b.Property<int?>("MetodoPago")
                        .HasColumnType("integer");

                    b.Property<decimal>("MontoPagado")
                        .HasColumnType("decimal(10,2)");

                    b.Property<string>("NumeroOperacion")
                        .HasColumnType("text");

                    b.Property<Guid>("PartidoId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CodigoConfirmacion")
                        .IsUnique();

                    b.HasIndex("JugadorId");

                    b.HasIndex("PartidoId");

                    b.ToTable("Reservas", "public");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Usuario", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<DateTime>("FechaRegistro")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("NombreCompleto")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rol")
                        .HasColumnType("integer");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("aaaaaaaa-aaaa-aaaa-aaaa-aaaaaaaaaaaa"),
                            Activo = true,
                            Email = "admin@adhsoftsport.com",
                            FechaRegistro = new DateTime(2026, 1, 1, 0, 0, 0, 0, DateTimeKind.Utc),
                            NombreCompleto = "Administrador ADHSOFT SPORT",
                            PasswordHash = "$2a$11$uQN3rv6/PtDi6FT8pKekdeQYsTUhiUTNxIrIpxTaumz5r1eZtm0iC",
                            Rol = 1,
                            Telefono = "+51999000000"
                        });
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Zona", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("Activo")
                        .HasColumnType("boolean");

                    b.Property<string>("Departamento")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.ToTable("Zonas", "public");

                    b.HasData(
                        new
                        {
                            Id = new Guid("11111111-1111-1111-1111-111111111111"),
                            Activo = true,
                            Departamento = "Lima",
                            Nombre = "Miraflores"
                        },
                        new
                        {
                            Id = new Guid("22222222-2222-2222-2222-222222222222"),
                            Activo = true,
                            Departamento = "Lima",
                            Nombre = "San Isidro"
                        },
                        new
                        {
                            Id = new Guid("33333333-3333-3333-3333-333333333333"),
                            Activo = true,
                            Departamento = "Lima",
                            Nombre = "Surco"
                        },
                        new
                        {
                            Id = new Guid("44444444-4444-4444-4444-444444444444"),
                            Activo = true,
                            Departamento = "Lima",
                            Nombre = "La Molina"
                        },
                        new
                        {
                            Id = new Guid("55555555-5555-5555-5555-555555555555"),
                            Activo = true,
                            Departamento = "Lima",
                            Nombre = "San Borja"
                        });
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Cancha", b =>
                {
                    b.HasOne("HSPichanga.Domain.Entities.Zona", "Zona")
                        .WithMany("Canchas")
                        .HasForeignKey("ZonaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Zona");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Club", b =>
                {
                    b.HasOne("HSPichanga.Domain.Entities.Usuario", "Delegado")
                        .WithMany("Clubs")
                        .HasForeignKey("DelegadoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Delegado");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.HorarioDisponible", b =>
                {
                    b.HasOne("HSPichanga.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Horarios")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cancha");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Partido", b =>
                {
                    b.HasOne("HSPichanga.Domain.Entities.Cancha", "Cancha")
                        .WithMany("Partidos")
                        .HasForeignKey("CanchaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSPichanga.Domain.Entities.HorarioDisponible", "Horario")
                        .WithMany("Partidos")
                        .HasForeignKey("HorarioId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("HSPichanga.Domain.Entities.Usuario", "Organizador")
                        .WithMany("PartidosOrganizados")
                        .HasForeignKey("OrganizadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Cancha");

                    b.Navigation("Horario");

                    b.Navigation("Organizador");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Reserva", b =>
                {
                    b.HasOne("HSPichanga.Domain.Entities.Usuario", "Jugador")
                        .WithMany("Reservas")
                        .HasForeignKey("JugadorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("HSPichanga.Domain.Entities.Partido", "Partido")
                        .WithMany("Reservas")
                        .HasForeignKey("PartidoId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Jugador");

                    b.Navigation("Partido");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Cancha", b =>
                {
                    b.Navigation("Horarios");

                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.HorarioDisponible", b =>
                {
                    b.Navigation("Partidos");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Partido", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("Clubs");

                    b.Navigation("PartidosOrganizados");

                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("HSPichanga.Domain.Entities.Zona", b =>
                {
                    b.Navigation("Canchas");
                });
#pragma warning restore 612, 618
        }
    }
}
